using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestApiJwt.Models
{


    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }

        [Column(TypeName = "decimal(19,4)")]
        public decimal ProductPrice { get; set; }
        public string ProductImage { get; set; }

        public int CategoryId { get; set; }
        public Category? Category { get; set; }
    }
}

