using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TestApiJwt.Models;

public class Shop
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
    public int ShopId { get; set; }
    public string ShopName { get; set; }
    public double ShopLocationLatitude { get; set; }
    public double ShopLocationLongitude { get; set; }
    public string ShopDescription { get; set; }
    
    public bool IsApproved { get; set; }
   
    public string UserId { get; set; }
    public ApplicationUser? User { get; set; }
    public ICollection<Category>? Categories { get; set; }

    public ICollection<Favorite>? Favorites { get; set; }
    public ICollection<Rating>? Rates { get; set; }
    public ICollection<Sale>? Sales { get; set; }   
}
