using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TestApiJwt.Models;

public class Shop
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
    public int ShopId { get; set; }
    public string ShopName { get; set; }
    public double ShopLocationLatitude { get; set; }
    public double ShopLocationLongitude { get; set; }
    public string ShopDescription { get; set; }
    /// <summary>
    /// category
    /// </summary>
    public bool IsApproved { get; set; }
    // Add other shop-related properties

    // Foreign key to link a shop to a user
    public string UserId { get; set; }
    public ApplicationUser? User { get; set; }
    public ICollection<Product>? Products { get; set; }
}
